import countryKeywords from "../../../temporary/countryKeywords.json";

// GDELT's Geo_CountryCode fields (where an event physically happened) use
// FIPS 10-4 two-letter codes, not ISO
const FIPS_BY_COUNTRY = {
  afghanistan: "AF",
  albania: "AL",
  algeria: "AG",
  angola: "AO",
  argentina: "AR",
  armenia: "AM",
  australia: "AS",
  austria: "AU",
  azerbaijan: "AJ",
  bahrain: "BA",
  bangladesh: "BG",
  belarus: "BO",
  belgium: "BE",
  belize: "BH",
  benin: "BN",
  bhutan: "BT",
  bolivia: "BL",
  "bosnia and herzegovina": "BK",
  botswana: "BC",
  brazil: "BR",
  brunei: "BX",
  bulgaria: "BU",
  "burkina faso": "UV",
  burundi: "BY",
  cambodia: "CB",
  cameroon: "CM",
  canada: "CA",
  "central african republic": "CT",
  chad: "CD",
  chile: "CI",
  china: "CH",
  colombia: "CO",
  comoros: "CN",
  "costa rica": "CS",
  croatia: "HR",
  cuba: "CU",
  czechia: "EZ",
  "democratic republic of congo": "CG",
  "dr congo": "CG",
  denmark: "DA",
  djibouti: "DJ",
  "dominican republic": "DR",
  "east timor": "TT",
  ecuador: "EC",
  egypt: "EG",
  "el salvador": "ES",
  "equatorial guinea": "EK",
  eritrea: "ER",
  estonia: "EN",
  eswatini: "WZ",
  ethiopia: "ET",
  finland: "FI",
  france: "FR",
  gabon: "GB",
  gambia: "GA",
  georgia: "GG",
  germany: "GM",
  ghana: "GH",
  greece: "GR",
  guatemala: "GT",
  guinea: "GV",
  "guinea-bissau": "PU",
  guyana: "GY",
  haiti: "HA",
  honduras: "HO",
  hungary: "HU",
  india: "IN",
  indonesia: "ID",
  iran: "IR",
  iraq: "IZ",
  ireland: "EI",
  israel: "IS",
  italy: "IT",
  "ivory coast": "IV",
  jamaica: "JM",
  japan: "JA",
  jordan: "JO",
  kazakhstan: "KZ",
  kenya: "KE",
  kosovo: "KV",
  kuwait: "KU",
  kyrgyzstan: "KG",
  laos: "LA",
  latvia: "LG",
  lebanon: "LE",
  liberia: "LI",
  libya: "LY",
  lithuania: "LH",
  luxembourg: "LU",
  madagascar: "MA",
  malawi: "MI",
  malaysia: "MY",
  mali: "ML",
  mauritania: "MR",
  mexico: "MX",
  moldova: "MD",
  mongolia: "MG",
  montenegro: "MJ",
  morocco: "MO",
  mozambique: "MZ",
  myanmar: "BM",
  namibia: "WA",
  nepal: "NP",
  netherlands: "NL",
  "new zealand": "NZ",
  nicaragua: "NU",
  niger: "NG",
  nigeria: "NI",
  "north korea": "KN",
  "north macedonia": "MK",
  norway: "NO",
  oman: "MU",
  pakistan: "PK",
  palestine: ["WE", "GZ"],
  panama: "PM",
  "papua new guinea": "PP",
  paraguay: "PA",
  peru: "PE",
  philippines: "RP",
  poland: "PL",
  portugal: "PO",
  qatar: "QA",
  "republic of congo": "CF",
  romania: "RO",
  russia: "RS",
  rwanda: "RW",
  "saudi arabia": "SA",
  senegal: "SG",
  serbia: "RI",
  "sierra leone": "SL",
  singapore: "SN",
  slovakia: "LO",
  slovenia: "SI",
  somalia: "SO",
  somaliland: "SO",
  "south africa": "SF",
  "south korea": "KS",
  "south sudan": "OD",
  spain: "SP",
  "sri lanka": "CE",
  sudan: "SU",
  sweden: "SW",
  switzerland: "SZ",
  syria: "SY",
  taiwan: "TW",
  tajikistan: "TI",
  tanzania: "TZ",
  thailand: "TH",
  togo: "TO",
  "trinidad and tobago": "TD",
  tunisia: "TS",
  turkey: "TU",
  turkmenistan: "TX",
  uganda: "UG",
  ukraine: "UP",
  "united arab emirates": "AE",
  "united kingdom": "UK",
  "united states of america": "US",
  uruguay: "UY",
  uzbekistan: "UZ",
  venezuela: "VE",
  vietnam: "VM",
  "western sahara": "WI",
  yemen: "YM",
  zambia: "ZA",
  zimbabwe: "ZI",
};

function normalizeCountryKey(value = "") {
  return value
    .toString()
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ");
}

// returns an array of FIPS codes for a country name or topic key
export function getFipsCodes(countryOrTopic) {
  const normalized = normalizeCountryKey(countryOrTopic);
  const aliases = countryKeywords.aliases || {};
  const resolvedKey = aliases[normalized] || normalized;

  const match = FIPS_BY_COUNTRY[normalized] || FIPS_BY_COUNTRY[resolvedKey];
  if (!match) return [];
  return Array.isArray(match) ? match : [match];
}

// track relevant FIPS codes
export function getAllTrackedFipsCodes() {
  const codes = new Set();
  for (const value of Object.values(FIPS_BY_COUNTRY)) {
    if (Array.isArray(value)) {
      value.forEach((code) => codes.add(code));
    } else {
      codes.add(value);
    }
  }
  return codes;
}
