const ACTOR_COUNTRY_NAMES = {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algeria",
  AGO: "Angola",
  ARG: "Argentina",
  ARM: "Armenia",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BLR: "Belarus",
  BEL: "Belgium",
  BLZ: "Belize",
  BEN: "Benin",
  BTN: "Bhutan",
  BOL: "Bolivia",
  BIH: "Bosnia and Herzegovina",
  BWA: "Botswana",
  BRA: "Brazil",
  BRN: "Brunei",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  KHM: "Cambodia",
  CMR: "Cameroon",
  CAN: "Canada",
  CAF: "Central African Republic",
  TCD: "Chad",
  CHL: "Chile",
  CHN: "China",
  COL: "Colombia",
  COM: "Comoros",
  CRI: "Costa Rica",
  HRV: "Croatia",
  CUB: "Cuba",
  CZE: "Czechia",
  COD: "DR Congo",
  DNK: "Denmark",
  DJI: "Djibouti",
  DOM: "Dominican Republic",
  TLS: "East Timor",
  ECU: "Ecuador",
  EGY: "Egypt",
  SLV: "El Salvador",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  EST: "Estonia",
  SWZ: "Eswatini",
  ETH: "Ethiopia",
  FIN: "Finland",
  FRA: "France",
  GAB: "Gabon",
  GMB: "Gambia",
  GEO: "Georgia",
  DEU: "Germany",
  GHA: "Ghana",
  GRC: "Greece",
  GTM: "Guatemala",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  GUY: "Guyana",
  HTI: "Haiti",
  HND: "Honduras",
  HUN: "Hungary",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Iran",
  IRQ: "Iraq",
  IRL: "Ireland",
  ISR: "Israel",
  ITA: "Italy",
  CIV: "Ivory Coast",
  JAM: "Jamaica",
  JPN: "Japan",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  XKX: "Kosovo",
  KWT: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Laos",
  LVA: "Latvia",
  LBN: "Lebanon",
  LBR: "Liberia",
  LBY: "Libya",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MDG: "Madagascar",
  MWI: "Malawi",
  MYS: "Malaysia",
  MLI: "Mali",
  MRT: "Mauritania",
  MEX: "Mexico",
  MDA: "Moldova",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NPL: "Nepal",
  NLD: "Netherlands",
  NZL: "New Zealand",
  NIC: "Nicaragua",
  NER: "Niger",
  NGA: "Nigeria",
  PRK: "North Korea",
  MKD: "North Macedonia",
  NOR: "Norway",
  OMN: "Oman",
  PAK: "Pakistan",
  PSE: "Palestine",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PHL: "Philippines",
  POL: "Poland",
  PRT: "Portugal",
  QAT: "Qatar",
  COG: "Republic of Congo",
  ROU: "Romania",
  RUS: "Russia",
  RWA: "Rwanda",
  SAU: "Saudi Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SLE: "Sierra Leone",
  SGP: "Singapore",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SOM: "Somalia",
  ZAF: "South Africa",
  KOR: "South Korea",
  SSD: "South Sudan",
  ESP: "Spain",
  LKA: "Sri Lanka",
  SDN: "Sudan",
  SWE: "Sweden",
  CHE: "Switzerland",
  SYR: "Syria",
  TWN: "Taiwan",
  TJK: "Tajikistan",
  TZA: "Tanzania",
  THA: "Thailand",
  TGO: "Togo",
  TTO: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Turkey",
  TKM: "Turkmenistan",
  UGA: "Uganda",
  UKR: "Ukraine",
  ARE: "United Arab Emirates",
  GBR: "United Kingdom",
  USA: "United States",
  URY: "Uruguay",
  UZB: "Uzbekistan",
  VEN: "Venezuela",
  VNM: "Vietnam",
  ESH: "Western Sahara",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabwe",
  IGO: "Intergovernmental Organization",
  UNO: "United Nations",
  EEC: "European Union",
  NATO: "NATO",
  IMF: "IMF",
};

const ACTOR_TYPE_LABELS = {
  AGR: "Agriculture",
  BUS: "Business",
  CRM: "Criminal",
  CVL: "Civilian",
  DEV: "Development",
  EDU: "Education",
  ELI: "Elite",
  ENV: "Environmental",
  GOV: "Government",
  HLH: "Health",
  HRI: "Human Rights",
  INS: "Insurgents",
  JUD: "Judicial",
  LAB: "Labor",
  LEG: "Legislature",
  MED: "Media",
  MIL: "Military",
  MNC: "Multinational Corporation",
  NGO: "NGO",
  NGM: "Non-Gov't Movement",
  OPP: "Opposition",
  PTY: "Political Party",
  REB: "Rebel",
  REF: "Refugees/IDPs",
  SEP: "Separatist",
  SET: "Settler",
  SPY: "Intelligence",
  UAF: "Unaligned Armed Forces",
};

export function decodeActor(actorCode) {
  if (!actorCode) return null;

  const chunks = actorCode.match(/.{1,3}/g) || [];
  let countryName = null;
  const roles = [];
  const unrecognized = [];

  for (const chunk of chunks) {
    if (!countryName && ACTOR_COUNTRY_NAMES[chunk]) {
      countryName = ACTOR_COUNTRY_NAMES[chunk];
    } else if (ACTOR_TYPE_LABELS[chunk]) {
      roles.push(ACTOR_TYPE_LABELS[chunk]);
    } else {
      unrecognized.push(chunk);
    }
  }

  if (!countryName && roles.length === 0) {
    return { code: actorCode, label: actorCode };
  }

  const parts = [countryName, ...roles].filter(Boolean);
  if (unrecognized.length > 0) parts.push(unrecognized.join(""));

  return {
    code: actorCode,
    label: parts.join(" — "),
    country: countryName,
    roles,
  };
}
