export const CAMEO_ROOT_CATEGORIES = [
  { code: "01", label: "Statement" },
  { code: "02", label: "Appeal" },
  { code: "03", label: "Intent to Cooperate" },
  { code: "04", label: "Consult" },
  { code: "05", label: "Diplomatic Cooperation" },
  { code: "06", label: "Material Cooperation" },
  { code: "07", label: "Provide Aid" },
  { code: "08", label: "Yield" },
  { code: "09", label: "Investigate" },
  { code: "10", label: "Demand" },
  { code: "11", label: "Disapprove" },
  { code: "12", label: "Reject" },
  { code: "13", label: "Threaten" },
  { code: "14", label: "Protest" },
  { code: "15", label: "Exhibit Force Posture" },
  { code: "16", label: "Reduce Relations" },
  { code: "17", label: "Coerce" },
  { code: "18", label: "Assault" },
  { code: "19", label: "Fight" },
  { code: "20", label: "Mass Violence" },
];
